/**
 * College / challenge enrolment.
 *
 * A student joins an institutional programme by typing a code during normal
 * sign-up. There is deliberately no separate account, invitation to accept, or
 * approval step: anything a student must do before their first session is a
 * place they drop out, and the whole product is built around removing those.
 *
 * The code is optional. Someone who found the app on their own must never be
 * blocked by a field meant for a campus rollout.
 */

/**
 * Codes are generated by the admin dashboard from an alphabet that excludes
 * characters people misread when a code is read aloud or printed on a poster:
 * no O/0, I/1, S/5, B/8.
 */
const CODE_PATTERN = /^[ACDEFGHJKLMNPQRTUVWXY349]{4,8}$/;

export type CodeCheck =
  | { state: 'empty' }
  | { state: 'invalid'; reason: string }
  | { state: 'valid'; code: string };

/** Normalises and validates the shape of a code. Does not check it exists. */
export function checkCode(raw: string): CodeCheck {
  const code = raw.trim().toUpperCase().replace(/\s+/g, '');

  if (code.length === 0) {
    return { state: 'empty' };
  }
  if (code.length < 4) {
    return { state: 'invalid', reason: 'Codes are at least 4 characters.' };
  }
  if (/[OIS0158]/.test(code)) {
    return {
      state: 'invalid',
      reason: 'Codes never contain O, I, S, 0, 1, 5 or 8 — check for a lookalike.',
    };
  }
  if (!CODE_PATTERN.test(code)) {
    return { state: 'invalid', reason: 'Letters and digits only.' };
  }
  return { state: 'valid', code };
}

/**
 * TODO: resolve the code against Firestore and enrol the student.
 *
 * Server-side, because a client that could write its own enrolment could add
 * itself to any college's cohort and distort that programme's reported numbers.
 * Expected shape: a callable Cloud Function that looks the code up, checks the
 * challenge is still open, and writes the membership.
 */
export async function redeemCode(code: string): Promise<void> {
  if (checkCode(code).state !== 'valid') {
    throw new Error('That code is not valid.');
  }
  // no-op until the backend exists
}
